# Generated by Django 5.2.5 on 2025-08-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restmans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Quản trị viên'), ('MANAGER', 'Quản lý'), ('WAITER', 'Phục vụ'), ('CUSTOMER', 'Khách hàng')], default='CUSTOMER', max_length=10, verbose_name='Vai trò'),
        ),
    ]
