# Generated by Django 5.2.5 on 2025-09-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restmans', '0003_order_table_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Trống'), ('OCCUPIED', 'Đang phục vụ'), ('CLEANING', 'Cần dọn dẹp')], default='AVAILABLE', max_length=10, verbose_name='Trạng thái bàn'),
        ),
    ]
