# Generated by Django 5.2.5 on 2025-09-06 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restmans', '0004_table_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('content', models.TextField(verbose_name='Nội dung phản hồi')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='restmans.review', verbose_name='Đánh giá gốc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên phản hồi')),
            ],
            options={
                'verbose_name': 'Phản hồi Đánh giá',
                'verbose_name_plural': 'Các Phản hồi Đánh giá',
                'ordering': ['created_date'],
            },
        ),
    ]
