# Generated by Django 5.2.5 on 2025-09-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restmans', '0005_reviewreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Đã xác nhận'), ('PENDING', 'Đang chờ'), ('CANCELLED', 'Đã hủy'), ('COMPLETED', 'Đã hoàn thành')], default='PENDING', max_length=10, verbose_name='Trạng thái'),
        ),
    ]
