"""
Django settings for restmanapis project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=x8olzwzlv3994davoqillqn#6f3$4%pq8**h5$^pm+3io-2+j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'restmans.apps.RestmansConfig',
    'ckeditor',
    'ckeditor_uploader',
    'rest_framework',
    'drf_yasg',
    'oauth2_provider',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

# === CẤU HÌNH GỬI EMAIL ===
# Sử dụng backend SMTP của Django
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# Máy chủ gửi mail của Gmail
EMAIL_HOST = 'smtp.gmail.com'
# Cổng SMTP
EMAIL_PORT = 587
# Sử dụng Transport Layer Security (TLS)
EMAIL_USE_TLS = True
# Tài khoản email của bạn
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
# Mật khẩu ứng dụng của tài khoản email
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
# Email mặc định sẽ hiển thị ở phần "From"
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")

# Cấu hình MoMo - BẠN NÊN ĐẶT CÁC GIÁ TRỊ NÀY TRONG settings.py
MOMO_ENDPOINT = "https://test-payment.momo.vn/v2/gateway/api/create"
MOMO_PARTNER_CODE = "MOMO"  # Thay bằng Partner Code của bạn
MOMO_ACCESS_KEY = config("MOMO_ACCESS_KEY")  # Thay bằng Access Key của bạn
MOMO_SECRET_KEY = config("MOMO_SECRET_KEY")  # Thay bằng Secret Key của bạn
MOMO_IPN_URL = "https://006a26554c86.ngrok-free.app/momo/"  # Thay bằng URL IPN thật của bạn
MOMO_REDIRECT_URL = "https://006a26554c86.ngrok-free.app/momo/return"  # Thay bằng URL Redirect thật của bạn

# === CẤU HÌNH VNPAY ===
VNPAY_ENDPOINT = "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
VNPAY_TMNCODE = config("VNPAY_TMNCODE")  # Lấy từ VNPay
VNPAY_HASH_SECRET_KEY = config("VNPAY_HASH_SECRET_KEY") # Lấy từ VNPay
VNPAY_RETURN_URL = "https://006a26554c86.ngrok-free.app/vnpay/return/" # URL front-end để khách hàng quay về
# URL IPN cần ngrok để test, ví dụ: "https://your-ngrok.ngrok-free.app/vnpay/ipn/"
VNPAY_IPN_URL = "https://006a26554c86.ngrok-free.app/vnpay/"

CORS_ALLOW_ALL_ORIGINS = True

import cloudinary
import cloudinary.uploader
from cloudinary.utils import cloudinary_url

# Configuration
cloudinary.config(
    cloud_name = config("CLOUD_NAME"),
    api_key = config("CLOUD_API_KEY"),
    api_secret = config("CLOUD_API_SECRET"),
    secure=True
)

ROOT_URLCONF = 'restmanapis.urls'

MEDIA_ROOT = '%s/restmans/static/' % BASE_DIR

CKEDITOR_UPLOAD_PATH = "ckeditors/dishes/"

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ( 'oauth2_provider.contrib.rest_framework.OAuth2Authentication',)
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'restmanapis.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'restmandb',
        'USER': 'root',
        'PASSWORD': 'Admin@123',
        'HOST': '',
    }
}

import pymysql

pymysql.install_as_MySQLdb()

AUTH_USER_MODEL = 'restmans.User'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

OAUTH2_PROVIDER = { 'OAUTH2_BACKEND_CLASS': 'oauth2_provider.oauth2_backends.JSONOAuthLibCore' }

CLIENT_ID = config("CLIENT_ID")
CLIENT_SECRET = config("CLIENT_SECRET")

GEMINI_API_KEY = config("GEMINI_API_KEY")

JAZZMIN_SETTINGS = {
    # Tiêu đề hiển thị trên tab trình duyệt (tối đa 50 ký tự)
    "site_title": "Quản trị Nhà hàng Tâm An",

    # Tiêu đề hiển thị trên trang đăng nhập và trên cùng bên trái
    "site_header": "Nhà hàng Tâm An",

    # Logo cho trang quản trị. Đặt file logo vào thư mục static của bạn.
    # Ví dụ: "img/logo.png"
    "site_logo": "path/to/your/logo.png",

    # Logo hiển thị trên trang đăng nhập
    "login_logo": "path/to/your/login_logo.png",

    # Chữ hiển thị ở cuối trang
    "copyright": "Nhà hàng Tâm An Ltd",

    # === GIAO DIỆN ===
    # Sử dụng theme mặc định (có thể đổi sang các theme khác như "cerulean", "cyborg", "darkly", ...)
    "theme": "default",

    # Giao diện cho các nút bấm và thành phần
    "UI_TWEAKS": {
        "navbar_small_text": False,
        "footer_small_text": False,
        "body_small_text": False,
        "brand_small_text": False,
        "brand_colour": "navbar-success",  # Màu của header
        "accent": "accent-primary",
        "navbar": "navbar-dark",
        "no_navbar_border": False,
        "sidebar": "sidebar-dark-primary",  # Màu của sidebar
        "sidebar_nav_small_text": False,
        "sidebar_disable_expand": False,
        "sidebar_nav_child_indent": False,
        "sidebar_nav_compact_style": False,
        "sidebar_nav_legacy_style": False,
        "sidebar_nav_flat_style": False,
        "theme": "default",
        "button_classes": {
            "primary": "btn-primary",
            "secondary": "btn-secondary",
            "info": "btn-info",
            "warning": "btn-warning",
            "danger": "btn-danger",
            "success": "btn-success"
        }
    },

    # === MENU BÊN CẠNH (SIDEBAR) ===
    # Tùy chỉnh các icon và thứ tự hiển thị của các model
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "restmans.Category": "fas fa-utensils",
        "restmans.Dish": "fas fa-concierge-bell",
        "restmans.Order": "fas fa-file-invoice-dollar",
        "restmans.Table": "fas fa-chair",
        "restmans.Booking": "fas fa-calendar-check",
        "restmans.Review": "fas fa-star",
    },

    # Hiển thị model nào lên đầu
    "topmenu_links": [
        {"name": "Trang chủ", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"app": "restmans", "name": "Quản lý Nhà hàng"},
    ],
}