"""
Django settings for restmanapis project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-=x8olzwzlv3994davoqillqn#6f3$4%pq8**h5$^pm+3io-2+j'
#
# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# Thành
SECRET_KEY = config('SECRET_KEY', default='django-insecure-=x8olzwzlv3994davoqillqn#6f3$4%pq8**h5$^pm+3io-2+j')
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'restmans.apps.RestmansConfig',
    'ckeditor',
    'ckeditor_uploader',
    'rest_framework',
    'drf_yasg',
    'oauth2_provider',
    'corsheaders',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # ← lên đầu tiên
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # ← thêm dòng này
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# === CẤU HÌNH GỬI EMAIL ===
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")

# === CẤU HÌNH MOMO ===
MOMO_ENDPOINT = "https://test-payment.momo.vn/v2/gateway/api/create"
MOMO_PARTNER_CODE = "MOMO"
MOMO_ACCESS_KEY = config("MOMO_ACCESS_KEY")
MOMO_SECRET_KEY = config("MOMO_SECRET_KEY")
MOMO_IPN_URL = "https://6a0c58b4f13e.ngrok-free.app/momo/"
MOMO_REDIRECT_URL = "https://6a0c58b4f13e.ngrok-free.app/momo/return"

# === CẤU HÌNH VNPAY ===
VNPAY_ENDPOINT = "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
VNPAY_TMNCODE = config("VNPAY_TMNCODE")
VNPAY_HASH_SECRET_KEY = config("VNPAY_HASH_SECRET_KEY")
VNPAY_RETURN_URL = "https://7c44167515be.ngrok-free.app/vnpay/return/"
VNPAY_IPN_URL = "https://7c44167515be.ngrok-free.app/vnpay/"

CORS_ALLOW_ALL_ORIGINS = True

import cloudinary
import cloudinary.uploader
from cloudinary.utils import cloudinary_url

# Configuration
cloudinary.config(
    cloud_name = config("CLOUD_NAME"),
    api_key = config("CLOUD_API_KEY"),
    api_secret = config("CLOUD_API_SECRET"),
    secure=True
)

ROOT_URLCONF = 'restmanapis.urls'

MEDIA_ROOT = '%s/restmans/static/' % BASE_DIR

CKEDITOR_UPLOAD_PATH = "ckeditors/dishes/"

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ( 'oauth2_provider.contrib.rest_framework.OAuth2Authentication',)
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'restmanapis.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'restmandb',
#         'USER': 'root',
#         'PASSWORD': 'Admin@123',
#         'HOST': '',
#     }
# }

# Thay toàn bộ DATABASES
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME', default='railway'),
        'USER': config('DB_USER', default='root'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='tramway.proxy.rlwy.net'),
        'PORT': config('DB_PORT', default='18971'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

CSRF_TRUSTED_ORIGINS = [
    'https://restaurantmanagement-production-3174.up.railway.app',
]

import pymysql

pymysql.install_as_MySQLdb()

AUTH_USER_MODEL = 'restmans.User'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # ← thêm dòng này
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'  # ← thêm dòng này

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

OAUTH2_PROVIDER = { 'OAUTH2_BACKEND_CLASS': 'oauth2_provider.oauth2_backends.JSONOAuthLibCore' }

CLIENT_ID = config("CLIENT_ID")
CLIENT_SECRET = config("CLIENT_SECRET")

GEMINI_API_KEY = config("GEMINI_API_KEY")

JAZZMIN_SETTINGS = {
    "site_title": "Quản trị Nhà hàng SpicyTown",
    "site_header": "Nhà hàng SpicyTown",
    "site_brand": "Hệ thống Quản lý",
    "welcome_sign": "Xin chào quản trị viên",
    "copyright": "© Nhà hàng SpicyTown",

    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "restmans.Category": "fas fa-list",
        "restmans.Dish": "fas fa-utensils",
        "restmans.Order": "fas fa-file-invoice-dollar",
        "restmans.Table": "fas fa-chair",
        "restmans.Booking": "fas fa-calendar-check",
        "restmans.Review": "fas fa-star",
    },

    "hide_apps": ["oauth2_provider", "drf_yasg", "corsheaders"],

    "topmenu_links": [
        {"name": "Trang chủ", "url": "admin:index"},
        {"name": "Thống kê", "url": "/admin/statistics/"},
        {"app": "restmans"},
    ],
}

JAZZMIN_UI_TWEAKS = {
    "theme": "default",
    "navbar": "navbar-dark",
    "brand_colour": "navbar-success",
    "accent": "accent-primary",
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "button_classes": {
        "primary": "btn btn-success",
        "secondary": "btn btn-secondary",
        "info": "btn btn-info",
        "warning": "btn btn-warning",
        "danger": "btn btn-danger",
    },
}