"""
Django settings for restmanapis project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=x8olzwzlv3994davoqillqn#6f3$4%pq8**h5$^pm+3io-2+j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'restmans.apps.RestmansConfig',
    'ckeditor',
    'ckeditor_uploader',
    'rest_framework',
    'drf_yasg',
    'oauth2_provider',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

# === CẤU HÌNH GỬI EMAIL ===
# Sử dụng backend SMTP của Django
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# Máy chủ gửi mail của Gmail
EMAIL_HOST = 'smtp.gmail.com'
# Cổng SMTP
EMAIL_PORT = 587
# Sử dụng Transport Layer Security (TLS)
EMAIL_USE_TLS = True
# Tài khoản email của bạn
EMAIL_HOST_USER = 'haopc1404@gmail.com'
# Mật khẩu ứng dụng của tài khoản email
EMAIL_HOST_PASSWORD = 'fglztnymslybrmzq'
# Email mặc định sẽ hiển thị ở phần "From"
DEFAULT_FROM_EMAIL = 'haopc1404@gmail.com'

# Cấu hình MoMo - BẠN NÊN ĐẶT CÁC GIÁ TRỊ NÀY TRONG settings.py
MOMO_ENDPOINT = "https://test-payment.momo.vn/v2/gateway/api/create"
MOMO_PARTNER_CODE = "MOMO"  # Thay bằng Partner Code của bạn
MOMO_ACCESS_KEY = "F8BBA842ECF85"  # Thay bằng Access Key của bạn
MOMO_SECRET_KEY = "K951B6PE1waDMi640xX08PD3vg6EkVlz"  # Thay bằng Secret Key của bạn
MOMO_IPN_URL = "https://localhost:8000/momo/"  # Thay bằng URL IPN thật của bạn
MOMO_REDIRECT_URL = "https://localhost:8000/momo/"  # Thay bằng URL Redirect thật của bạn

# === CẤU HÌNH VNPAY ===
VNPAY_ENDPOINT = "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
VNPAY_TMNCODE = "LSGEFJZL"  # Lấy từ VNPay
VNPAY_HASH_SECRET_KEY = "54BE9GO6556S6E94KB9VLV46XLHTYEKM" # Lấy từ VNPay
VNPAY_RETURN_URL = "https://9318144ca538.ngrok-free.app/vnpay/return/" # URL front-end để khách hàng quay về
# URL IPN cần ngrok để test, ví dụ: "https://your-ngrok.ngrok-free.app/vnpay/ipn/"
VNPAY_IPN_URL = "https://9318144ca538.ngrok-free.app/vnpay/"

CORS_ALLOW_ALL_ORIGINS = True

import cloudinary
import cloudinary.uploader
from cloudinary.utils import cloudinary_url

# Configuration
cloudinary.config(
    cloud_name = "dbitlfhjx",
    api_key = "889556431667884",
    api_secret = "ycTIF7ajW7_lKzO_Ff4zAwpeB6g",
    secure=True
)

ROOT_URLCONF = 'restmanapis.urls'

MEDIA_ROOT = '%s/restmans/static/' % BASE_DIR

CKEDITOR_UPLOAD_PATH = "ckeditors/dishes/"

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ( 'oauth2_provider.contrib.rest_framework.OAuth2Authentication',)
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'restmanapis.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'restmandb',
        'USER': 'root',
        'PASSWORD': 'Admin@123',
        'HOST': '',
    }
}

import pymysql

pymysql.install_as_MySQLdb()

AUTH_USER_MODEL = 'restmans.User'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

OAUTH2_PROVIDER = { 'OAUTH2_BACKEND_CLASS': 'oauth2_provider.oauth2_backends.JSONOAuthLibCore' }

CLIENT_ID = 'iQnD8RzJ1ECAqR9IH4FoyDJW7p8T9R40n2IEQrHz'
CLIENT_SECRET = 'VSmBl2VTdylEm6ts68nQkRPHtXgIGnNAJsQPIDempHG4EYpWhjbfq5HRIRWQRqt7njdc1rE2Gbtu5HBk7pc4zYpUmWZmKWYx9x4jb08Rb1jgVRP2XciMurzHN9qvHbe2'
